name: Monitor Sebo Cultural

on:
  schedule:
    - cron: '0 */2 * * *' # Roda a cada 2 horas
  workflow_dispatch: # Permite que você clique em um botão para rodar manualmente e testar

jobs:
  verificar_loja:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necessário para o bot poder salvar o arquivo .json

    steps:
      - name: Baixar os arquivos do repositório
        uses: actions/checkout@v4

      - name: Preparar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar bibliotecas
        run: pip install -r requirements.txt

      - name: Rodar o script de monitoramento
        run: python monitor.py

      - name: Salvar a memória (Commit do JSON)
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add jogos_vistos.json
          # O comando abaixo tenta fazer o commit. Se não houver nada novo, ele sai silenciosamente.
          git commit -m "Atualiza memória de jogos encontrados" || exit 0
          git push